/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as AuthenticatedCreatePollRouteImport } from './routes/_authenticated/create-poll'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as PollsIndexRouteImport } from './routes/polls/index'
import { Route as PollsPollIdRouteImport } from './routes/polls/$pollId'
import { Route as AuthenticatedAnalyticsPollIdRouteImport } from './routes/_authenticated/analytics/$pollId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCreatePollRoute = AuthenticatedCreatePollRouteImport.update({
  id: '/_authenticated/create-poll',
  path: '/create-poll',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/_authenticated/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const PollsIndexRoute = PollsIndexRouteImport.update({
  id: '/polls/',
  path: '/polls/',
  getParentRoute: () => rootRouteImport,
} as any)
const PollsPollIdRoute = PollsPollIdRouteImport.update({
  id: '/polls/$pollId',
  path: '/polls/$pollId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyticsPollIdRoute =
  AuthenticatedAnalyticsPollIdRouteImport.update({
    id: '/_authenticated/analytics/$pollId',
    path: '/analytics/$pollId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/create-poll': typeof AuthenticatedCreatePollRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/polls/$pollId': typeof PollsPollIdRoute
  '/polls/': typeof PollsIndexRoute
  '/analytics/$pollId': typeof AuthenticatedAnalyticsPollIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/create-poll': typeof AuthenticatedCreatePollRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/polls/$pollId': typeof PollsPollIdRoute
  '/polls': typeof PollsIndexRoute
  '/analytics/$pollId': typeof AuthenticatedAnalyticsPollIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/_authenticated/create-poll': typeof AuthenticatedCreatePollRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/polls/$pollId': typeof PollsPollIdRoute
  '/polls/': typeof PollsIndexRoute
  '/_authenticated/analytics/$pollId': typeof AuthenticatedAnalyticsPollIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/create-poll'
    | '/dashboard'
    | '/polls/$pollId'
    | '/polls/'
    | '/analytics/$pollId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/create-poll'
    | '/dashboard'
    | '/polls/$pollId'
    | '/polls'
    | '/analytics/$pollId'
  id:
    | '__root__'
    | '/'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/_authenticated/create-poll'
    | '/_authenticated/dashboard'
    | '/polls/$pollId'
    | '/polls/'
    | '/_authenticated/analytics/$pollId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
  AuthenticatedCreatePollRoute: typeof AuthenticatedCreatePollRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  PollsPollIdRoute: typeof PollsPollIdRoute
  PollsIndexRoute: typeof PollsIndexRoute
  AuthenticatedAnalyticsPollIdRoute: typeof AuthenticatedAnalyticsPollIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/create-poll': {
      id: '/_authenticated/create-poll'
      path: '/create-poll'
      fullPath: '/create-poll'
      preLoaderRoute: typeof AuthenticatedCreatePollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polls/': {
      id: '/polls/'
      path: '/polls'
      fullPath: '/polls/'
      preLoaderRoute: typeof PollsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polls/$pollId': {
      id: '/polls/$pollId'
      path: '/polls/$pollId'
      fullPath: '/polls/$pollId'
      preLoaderRoute: typeof PollsPollIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics/$pollId': {
      id: '/_authenticated/analytics/$pollId'
      path: '/analytics/$pollId'
      fullPath: '/analytics/$pollId'
      preLoaderRoute: typeof AuthenticatedAnalyticsPollIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
  AuthenticatedCreatePollRoute: AuthenticatedCreatePollRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  PollsPollIdRoute: PollsPollIdRoute,
  PollsIndexRoute: PollsIndexRoute,
  AuthenticatedAnalyticsPollIdRoute: AuthenticatedAnalyticsPollIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
