/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as authRegisterRouteImport } from './routes/(auth)/register'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAuthenticatedRouteRouteImport } from './routes/_app/_authenticated/route'
import { Route as AppAuthenticatedCreatePollRouteImport } from './routes/_app/_authenticated/create-poll'
import { Route as AppAuthenticatedDashboardRouteImport } from './routes/_app/_authenticated/dashboard'
import { Route as AppPollsIndexRouteImport } from './routes/_app/polls/index'
import { Route as AppPollsPollIdRouteImport } from './routes/_app/polls/$pollId'
import { Route as AppAuthenticatedAnalyticsPollIdRouteImport } from './routes/_app/_authenticated/analytics/$pollId'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/(auth)/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuthenticatedRouteRoute = AppAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuthenticatedCreatePollRoute =
  AppAuthenticatedCreatePollRouteImport.update({
    id: '/create-poll',
    path: '/create-poll',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppAuthenticatedDashboardRoute =
  AppAuthenticatedDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)
const AppPollsIndexRoute = AppPollsIndexRouteImport.update({
  id: '/polls/',
  path: '/polls/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPollsPollIdRoute = AppPollsPollIdRouteImport.update({
  id: '/polls/$pollId',
  path: '/polls/$pollId',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAuthenticatedAnalyticsPollIdRoute =
  AppAuthenticatedAnalyticsPollIdRouteImport.update({
    id: '/analytics/$pollId',
    path: '/analytics/$pollId',
    getParentRoute: () => AppAuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/create-poll': typeof AppAuthenticatedCreatePollRoute
  '/dashboard': typeof AppAuthenticatedDashboardRoute
  '/polls/$pollId': typeof AppPollsPollIdRoute
  '/polls/': typeof AppPollsIndexRoute
  '/analytics/$pollId': typeof AppAuthenticatedAnalyticsPollIdRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/login': typeof authLoginRoute
  '/register': typeof authRegisterRoute
  '/create-poll': typeof AppAuthenticatedCreatePollRoute
  '/dashboard': typeof AppAuthenticatedDashboardRoute
  '/polls/$pollId': typeof AppPollsPollIdRoute
  '/polls': typeof AppPollsIndexRoute
  '/analytics/$pollId': typeof AppAuthenticatedAnalyticsPollIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/_authenticated': typeof AppAuthenticatedRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/(auth)/register': typeof authRegisterRoute
  '/_app/': typeof AppIndexRoute
  '/_app/_authenticated/create-poll': typeof AppAuthenticatedCreatePollRoute
  '/_app/_authenticated/dashboard': typeof AppAuthenticatedDashboardRoute
  '/_app/polls/$pollId': typeof AppPollsPollIdRoute
  '/_app/polls/': typeof AppPollsIndexRoute
  '/_app/_authenticated/analytics/$pollId': typeof AppAuthenticatedAnalyticsPollIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/create-poll'
    | '/dashboard'
    | '/polls/$pollId'
    | '/polls/'
    | '/analytics/$pollId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/create-poll'
    | '/dashboard'
    | '/polls/$pollId'
    | '/polls'
    | '/analytics/$pollId'
  id:
    | '__root__'
    | '/_app'
    | '/_app/_authenticated'
    | '/(auth)/login'
    | '/(auth)/register'
    | '/_app/'
    | '/_app/_authenticated/create-poll'
    | '/_app/_authenticated/dashboard'
    | '/_app/polls/$pollId'
    | '/_app/polls/'
    | '/_app/_authenticated/analytics/$pollId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  authRegisterRoute: typeof authRegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/register': {
      id: '/(auth)/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_authenticated': {
      id: '/_app/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppAuthenticatedRouteRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_authenticated/create-poll': {
      id: '/_app/_authenticated/create-poll'
      path: '/create-poll'
      fullPath: '/create-poll'
      preLoaderRoute: typeof AppAuthenticatedCreatePollRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/_app/_authenticated/dashboard': {
      id: '/_app/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppAuthenticatedDashboardRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
    '/_app/polls/': {
      id: '/_app/polls/'
      path: '/polls'
      fullPath: '/polls/'
      preLoaderRoute: typeof AppPollsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/polls/$pollId': {
      id: '/_app/polls/$pollId'
      path: '/polls/$pollId'
      fullPath: '/polls/$pollId'
      preLoaderRoute: typeof AppPollsPollIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/_authenticated/analytics/$pollId': {
      id: '/_app/_authenticated/analytics/$pollId'
      path: '/analytics/$pollId'
      fullPath: '/analytics/$pollId'
      preLoaderRoute: typeof AppAuthenticatedAnalyticsPollIdRouteImport
      parentRoute: typeof AppAuthenticatedRouteRoute
    }
  }
}

interface AppAuthenticatedRouteRouteChildren {
  AppAuthenticatedCreatePollRoute: typeof AppAuthenticatedCreatePollRoute
  AppAuthenticatedDashboardRoute: typeof AppAuthenticatedDashboardRoute
  AppAuthenticatedAnalyticsPollIdRoute: typeof AppAuthenticatedAnalyticsPollIdRoute
}

const AppAuthenticatedRouteRouteChildren: AppAuthenticatedRouteRouteChildren = {
  AppAuthenticatedCreatePollRoute: AppAuthenticatedCreatePollRoute,
  AppAuthenticatedDashboardRoute: AppAuthenticatedDashboardRoute,
  AppAuthenticatedAnalyticsPollIdRoute: AppAuthenticatedAnalyticsPollIdRoute,
}

const AppAuthenticatedRouteRouteWithChildren =
  AppAuthenticatedRouteRoute._addFileChildren(
    AppAuthenticatedRouteRouteChildren,
  )

interface AppRouteRouteChildren {
  AppAuthenticatedRouteRoute: typeof AppAuthenticatedRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppPollsPollIdRoute: typeof AppPollsPollIdRoute
  AppPollsIndexRoute: typeof AppPollsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAuthenticatedRouteRoute: AppAuthenticatedRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppPollsPollIdRoute: AppPollsPollIdRoute,
  AppPollsIndexRoute: AppPollsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
  authRegisterRoute: authRegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
